### ISSUE TITLE
A file listed in the manifest cannot be found: freeplane-bin-1.12.5.ebuild

### ISSUE THREAD

**Issue by rharmonson** [logrusx/gentoo#1]
The app-misc/freeplane-bin/Manifest needs references to freeplane-bin-1.12.5 deleted for it doesn't exist. Editing Manifest and deleting 1.12.5 references permits installing freeplane-bin.

**Comment by logrusx** [comment]
Hello, 
Thank you for pointing that out. 

Could you please post the error message while I get back to the issue? 

Thanks!

**Comment by rharmonson** [comment]
> Hello,
>Thank you for pointing that out.
>
>Could you please post the error message while I get back to the issue?
>
>Thanks!

Here you go! :)

```
~ # emerge app-misc/freeplane-bin

    IMPORTANT: 24 news items need reading for repository 'gentoo'.
    Use eselect news read to view new items.

These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 1.77 s (backtrack: 0/20).

[ebuild N ~] app-misc/freeplane-bin-1.12.6::logrusx USE="-doc" 0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] y

            Verifying ebuild manifests

!!! A file listed in the Manifest could not be found: /var/db/repos/logrusx/app-misc/freeplane-bin/freeplane-bin-1.12.5.ebuild

~ #
```

**Comment by logrusx** [comment]
Sorry for the previous post, I was on the go and didn't figure out what you had written at first, but the second time around I got it, that's why I deleted the post.

It should be now fixed. Thank you for pointing it out!

**Comment by rharmonson** [comment]
No worries. I appreciate you maintaining the freeplane package and the quick response!

I have not delved into portage packaging and repositories--I have been only using Gentoo for a couple months. I do maintain a Debian repository and a few packages, so I need to explore how to create a Gentoo's repository and packaging. Any references you recommend outside of the official portage documentation?

Again, thank you!

**Comment by logrusx** [comment]
https://forums.gentoo.org/
https://wiki.gentoo.org/wiki/Main_Page
https://devmanual.gentoo.org/
#gentoo-dev-help at libera.chat IRC server.

Those are the resources I've used, mainly the devmanual and help from the folks in the IRC channel. There's also the eclass-manpages package, which contains, well the manual pages for the eclasses.
